### ISSUE TITLE
User Stories feedback

### ISSUE THREAD

**Issue by dfelleman811** [210823-java-msa-wvu/shailendra_nain_p0#1]
Hi Shailendra - this is a great start and a cool idea. I would suggest having only two type of users. A supervisor/manager and a donor. That way, a donor can (1) view upcoming blood drives, (2) edit their user information like address, (3) register for a blood drive. Then the supervisor/manager user can approve/deny the registration and create/delete blood drives. @shailnain6

**Comment by shailnain6** [comment]
Thanks for the guideline, made changes accordingly.
